// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.920
// internal/views/visualization_charts.templ

package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func VisualizationCharts(dataString string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"charts-wrapper\"><div class=\"chart-card\"><h3>Wartość aktywów</h3><canvas id=\"portfolioChart\"></canvas></div></div><script>\n\t\t// Dane z Go, które są umieszczone bezpośrednio w skrypcie\n\t\tconst data = JSON.parse(`{ !dataString }`);\n\t\tconst ctx = document.getElementById('portfolioChart').getContext('2d');\n\t\t\n\t\t// Sprawdź, czy wykres już istnieje na tym canvasie, i go zniszcz, jeśli tak\n\t\tconst existingChart = Chart.getChart(ctx);\n\t\tif (existingChart) {\n\t\t\texistingChart.destroy();\n\t\t}\n\n\t\tnew Chart(ctx, {\n\t\t\ttype: 'doughnut',\n\t\t\tdata: {\n\t\t\t\tlabels: data.labels,\n\t\t\t\tdatasets: [{\n\t\t\t\t\tlabel: 'Wartość aktywów',\n\t\t\t\t\tdata: data.values,\n\t\t\t\t\tbackgroundColor: [\n\t\t\t\t\t\t'rgba(255, 99, 132, 0.8)',\n\t\t\t\t\t\t'rgba(54, 162, 235, 0.8)',\n\t\t\t\t\t\t'rgba(255, 206, 86, 0.8)',\n\t\t\t\t\t\t'rgba(75, 192, 192, 0.8)',\n\t\t\t\t\t\t'rgba(153, 102, 255, 0.8)',\n\t\t\t\t\t\t'rgba(255, 159, 64, 0.8)'\n\t\t\t\t\t],\n\t\t\t\t\tborderColor: [\n\t\t\t\t\t\t'rgba(255, 99, 132, 1)',\n\t\t\t\t\t\t'rgba(54, 162, 235, 1)',\n\t\t\t\t\t\t'rgba(255, 206, 86, 1)',\n\t\t\t\t\t\t'rgba(75, 192, 192, 1)',\n\t\t\t\t\t\t'rgba(153, 102, 255, 1)',\n\t\t\t\t\t\t'rgba(255, 159, 64, 1)'\n\t\t\t\t\t],\n\t\t\t\t\tborderWidth: 1\n\t\t\t\t}]\n\t\t\t},\n\t\t\toptions: {\n\t\t\t\tresponsive: true,\n\t\t\t\tplugins: {\n\t\t\t\t\tlegend: {\n\t\t\t\t\t\tposition: 'top',\n\t\t\t\t\t},\n\t\t\t\t\ttitle: {\n\t\t\t\t\t\tdisplay: true,\n\t\t\t\t\t\ttext: 'Udział aktywów w portfelu'\n\t\t\t\t\t}\n\t\t\t\t}\n\t\t\t}\n\t\t});\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
